import { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import {
  FlaskConical,
  Plus,
  Play,
  CheckCircle2,
  XCircle,
  Clock,
  Sparkles,
  FileCode
} from 'lucide-react';
import clsx from 'clsx';
import { testingApi } from '../services/api';
import { TestSuite, TestCase } from '@local-code-agent/shared';

export const TestingPage = () => {
  const [selectedSuite, setSelectedSuite] = useState<TestSuite | null>(null);
  const [showCreateModal, setShowCreateModal] = useState(false);
  const queryClient = useQueryClient();

  const { data: testSuites, isLoading } = useQuery({
    queryKey: ['test-suites'],
    queryFn: async () => {
      const response = await testingApi.getAll();
      return response.data.data;
    },
  });

  const runTestsMutation = useMutation({
    mutationFn: (suiteId: string) => testingApi.run(suiteId),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['test-suites'] });
    },
  });

  const getTestStatusIcon = (status?: string) => {
    switch (status) {
      case 'passed':
        return <CheckCircle2 className="w-4 h-4 text-green-500" />;
      case 'failed':
        return <XCircle className="w-4 h-4 text-red-500" />;
      case 'running':
        return <Clock className="w-4 h-4 text-blue-500 animate-pulse" />;
      default:
        return <Clock className="w-4 h-4 text-gray-400" />;
    }
  };

  const getTestStatusColor = (status?: string) => {
    switch (status) {
      case 'passed':
        return 'bg-green-100 text-green-700';
      case 'failed':
        return 'bg-red-100 text-red-700';
      case 'running':
        return 'bg-blue-100 text-blue-700';
      default:
        return 'bg-gray-100 text-gray-700';
    }
  };

  const calculateSuiteStats = (suite: TestSuite) => {
    const total = suite.testCases.length;
    const passed = suite.testCases.filter(t => t.status === 'passed').length;
    const failed = suite.testCases.filter(t => t.status === 'failed').length;
    const pending = total - passed - failed;
    return { total, passed, failed, pending };
  };

  return (
    <div className="p-8 max-w-7xl mx-auto">
      {/* Header */}
      <div className="mb-8">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-3xl font-bold text-gray-900">Testing</h1>
            <p className="mt-2 text-gray-600">
              AI-powered test generation and automated test execution
            </p>
          </div>
          <button
            onClick={() => setShowCreateModal(true)}
            className="flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
          >
            <Plus className="w-5 h-5" />
            New Test Suite
          </button>
        </div>
      </div>

      {/* Test Suites List */}
      {isLoading ? (
        <div className="text-center py-12">
          <div className="inline-block animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"></div>
          <p className="mt-4 text-gray-600">Loading test suites...</p>
        </div>
      ) : testSuites && testSuites.length > 0 ? (
        <div className="grid grid-cols-1 gap-6">
          {testSuites.map((suite) => {
            const stats = calculateSuiteStats(suite);
            const passRate = stats.total > 0 ? (stats.passed / stats.total) * 100 : 0;

            return (
              <div
                key={suite.id}
                className="bg-white rounded-lg border border-gray-200 p-6 hover:shadow-lg transition-shadow cursor-pointer"
                onClick={() => setSelectedSuite(suite)}
              >
                <div className="flex items-start justify-between">
                  <div className="flex-1">
                    <div className="flex items-center gap-3">
                      <FlaskConical className="w-5 h-5 text-purple-600" />
                      <h3 className="text-lg font-semibold text-gray-900">
                        {suite.name}
                      </h3>
                      {suite.autoGenerated && (
                        <div className="flex items-center gap-1 px-2 py-1 bg-purple-100 text-purple-700 rounded text-xs font-medium">
                          <Sparkles className="w-3 h-3" />
                          AI Generated
                        </div>
                      )}
                      <div className={clsx(
                        'flex items-center gap-1 px-2 py-1 rounded text-xs font-medium',
                        getTestStatusColor(suite.status)
                      )}>
                        {getTestStatusIcon(suite.status)}
                        {suite.status || 'pending'}
                      </div>
                    </div>

                    {suite.description && (
                      <p className="mt-2 text-gray-600">{suite.description}</p>
                    )}

                    {suite.filePath && (
                      <div className="mt-2 flex items-center gap-2 text-sm text-gray-500">
                        <FileCode className="w-4 h-4" />
                        {suite.filePath}
                      </div>
                    )}

                    {/* Stats Bar */}
                    <div className="mt-4">
                      <div className="flex items-center gap-4 text-sm mb-2">
                        <div className="flex items-center gap-1">
                          <span className="font-medium">{stats.total}</span>
                          <span className="text-gray-500">tests</span>
                        </div>
                        {stats.passed > 0 && (
                          <div className="flex items-center gap-1 text-green-600">
                            <CheckCircle2 className="w-4 h-4" />
                            {stats.passed} passed
                          </div>
                        )}
                        {stats.failed > 0 && (
                          <div className="flex items-center gap-1 text-red-600">
                            <XCircle className="w-4 h-4" />
                            {stats.failed} failed
                          </div>
                        )}
                        {stats.pending > 0 && (
                          <div className="flex items-center gap-1 text-gray-500">
                            <Clock className="w-4 h-4" />
                            {stats.pending} pending
                          </div>
                        )}
                      </div>

                      {/* Progress Bar */}
                      <div className="h-2 bg-gray-200 rounded-full overflow-hidden">
                        <div
                          className="h-full bg-green-500 transition-all"
                          style={{ width: `${passRate}%` }}
                        />
                      </div>
                      <div className="text-xs text-gray-500 mt-1">
                        {passRate.toFixed(0)}% pass rate
                      </div>
                    </div>

                    {/* Test Cases Preview */}
                    {suite.testCases && suite.testCases.length > 0 && (
                      <div className="mt-4 space-y-2">
                        {suite.testCases.slice(0, 3).map((test, idx) => (
                          <div
                            key={idx}
                            className="flex items-start gap-2 p-2 rounded bg-gray-50"
                          >
                            {getTestStatusIcon(test.status)}
                            <div className="flex-1">
                              <div className="text-sm font-medium text-gray-900">
                                {test.name}
                              </div>
                              {test.error && (
                                <div className="text-xs text-red-600 mt-1">
                                  {test.error}
                                </div>
                              )}
                            </div>
                            {test.executionTime && (
                              <div className="text-xs text-gray-500">
                                {test.executionTime}ms
                              </div>
                            )}
                          </div>
                        ))}
                        {suite.testCases.length > 3 && (
                          <div className="text-sm text-gray-500 text-center">
                            +{suite.testCases.length - 3} more tests
                          </div>
                        )}
                      </div>
                    )}

                    <div className="mt-4 flex items-center gap-3 text-sm text-gray-500">
                      <div>Created: {new Date(suite.createdAt).toLocaleString()}</div>
                      {suite.lastRun && (
                        <div>Last run: {new Date(suite.lastRun).toLocaleString()}</div>
                      )}
                    </div>
                  </div>

                  <div className="ml-4">
                    <button
                      onClick={(e) => {
                        e.stopPropagation();
                        runTestsMutation.mutate(suite.id);
                      }}
                      disabled={suite.status === 'running'}
                      className="p-2 text-blue-600 hover:bg-blue-50 rounded-lg transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                      title="Run Tests"
                    >
                      <Play className="w-5 h-5" />
                    </button>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      ) : (
        <div className="text-center py-12 bg-white rounded-lg border border-gray-200">
          <FlaskConical className="w-12 h-12 text-gray-400 mx-auto mb-4" />
          <h3 className="text-lg font-medium text-gray-900 mb-2">No test suites yet</h3>
          <p className="text-gray-600 mb-4">
            Create your first test suite with AI-powered test generation
          </p>
          <button
            onClick={() => setShowCreateModal(true)}
            className="inline-flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
          >
            <Plus className="w-5 h-5" />
            Create Test Suite
          </button>
        </div>
      )}

      {/* Create Modal Placeholder */}
      {showCreateModal && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50">
          <div className="bg-white rounded-lg max-w-2xl w-full p-6">
            <h2 className="text-xl font-bold mb-4">Create Test Suite</h2>
            <p className="text-gray-600 mb-4">
              Test suite creation form with AI generation will be implemented here
            </p>
            <button
              onClick={() => setShowCreateModal(false)}
              className="px-4 py-2 bg-gray-200 text-gray-700 rounded-lg hover:bg-gray-300"
            >
              Close
            </button>
          </div>
        </div>
      )}
    </div>
  );
};
